[package]
name = "ongaku"
version = "0.0.1"
edition = "2021"
authors = ["Jorge Rinaldi <jrg.rinaldi@gmail.com>"]
license = "AGPL-3.0"
repository = "https://github.com/m-rinaldi/ongaku"
description = "MIDI-file tone generator"
#keywords = ["music", "midi"]

[dependencies]
local_vec = "0.4.0"
