[package]
name = "ongaku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local_vec = { git = "https://github.com/m-rinaldi/local_vec", branch = "dev" }

